apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener
spec:
  triggers:
    - name: event-listener-triggers
      bindings:
        - name: trigger-binding
      template:
        name: trigger-template
