apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: minha-primeira-task
spec:
  inputs:
    resources:
      - name: workspace
        type: git
    params:
      - name: bananinha
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-sources
      image: ubuntu
      script: |
        #!/usr/bin/env bash
        /workspace/classic-pipeline.sh  # provided by an input resource  