apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: minha-primeira-task
spec:
  inputs:
    resources:
      - name: workspace
        type: git
    params:
      - name: bananinha
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-sources
      image: ubuntu
      command: ["/bin/bash", "-c" ]
        # - /bin/bash
        # args: ["-c", "echo hello world" ]
      args:
        - |
          ls
          source classic-pipeline.sh