apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: minha-primeira-task
spec:
  resources:
    inputs:
      - name: src-repo
        type: git
    outputs:
      - name: baked-image
        type: image
  params:
    - name: bananinha
  steps:
    - name: build-sources
      image: ubuntu
      command:
        - /bin/bash
      args: ["-c", "echo hello world"]
