apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: minhaPrimeiraTask
spec:
  params:
    - name: param_name
      resources:
        - name: build-sources
          type: ubuntu
  steps:
    - name: build-sources
      image: ubuntu
      command:
        - /bin/bash
      args: ["-c", "echo hello world"]
