apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: minha-primeira-task
spec:
  inputs:
    resources:
      - name: workspace
        type: git
    params:
      - name: bananinha
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-sources
      image: ubuntu
      command: ["/bin/bash", "-c" ]
        # - /bin/bash
        # args: ["-c", "echo hello world" ]
      args:
        - |
          printf "\n ====================== apt-get update ======================\n"
          apt-get update
          printf "\n ====================== apt-get install ======================\n"
          apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y
          printf "\n ====================== cypress ci ======================\n"
          npm ci
          printf "\n ====================== cypress run ======================\n"
          npm run cy:run