apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: bananinha
  workspaces:
    - name: shared-workspace
  tasks:
    - name: regression-tests
      taskRef:
        name: cypress-task
      params:
        - name: bananinha
          value: $(params.bananinha)
      workspaces:
        - name: workspace
          workspace: shared-workspace
