apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: bananinha
  workspaces:
    - name: output
  tasks:
    - name: regression-tests
      taskRef:
        name: cypress-task
      workspaces:
        - name: output
          workspace: output
      params:
        - name: bananinha
          value: $(params.bananinha)
