apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: bananinha
  tasks:
    - name: e2e-tests
      taskRef:
        name: cypress-task
      params:
      - name: bananinha
        value: $(params.bananinha)