apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  workspaces:
    - name: git-source
  params:
    - name: clone_url
  tasks:
    - name: clone-repo
      taskRef:
        name: git-repo
      params:
        - name: url
          value: $(params.clone_url)
        - name: revision
          value: "main"  # Branch que deseja clonar
        - name: depth
          value: "1"  # Opcional: define a profundidade do clone
      workspaces:
        - name: output
          workspace: git-source
