apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: html_url
  workspaces:
    - name: git-source
  tasks:
    - name: clone-repo
      taskRef:
        name: cypress-task
      params:
        - name: html_url
          value: $(params.html_url)
        - name: revision
          value: "main"  # Branch que deseja clonar
        - name: depth
          value: "1"  # Opcional: define a profundidade do clone
      workspaces:
        - name: git-repo
          workspace: git-source
