apiVersion: v1
kind: Secret
metadata:
  name: git-ssh-key
  annotations:
    tekton.dev/git-0: github.com  # Substitua pelo domínio do seu Git
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    S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
    -----END OPENSSH PRIVATE KEY-----
