apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  params:
    - name: bananinha
  tasks:
    - name: uma-taks
      taskRef:
        name: minha-primeira-task
      params:
      - name: bananinha
        value: $(params.bananinha)
    - name: duas-taks
      taskRef:
        name: minha-segunda-task
      params:
      - name: bananinha
        value: $(params.bananinha)