apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cypress-task
spec:
  description: Read and display README file.
  steps:
    - name: git-clone
      image: ubuntu
      script: |
        #!/bin/sh
        echo "BANANA" > $(workspaces.sabrina.path)/cypress
        ls
    # - name: install-cypress
    #   image: ubuntu
    #   command:
    #     ["/bin/bash", "-c"]
    #     # - /bin/bash
    #     # args: ["-c", "echo hello world" ]
    #   args:
    #     - |
    #       ls
    # - name: run-cypress
    #   image: ubuntu
    #   command:
    #     ["/bin/bash", "-c"]
    #     # - /bin/bash
    #     # args: ["-c", "echo hello world" ]
    #   args:
    #     - |
    #       cd workspace/
    #       ls
