apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: output
  params:
    - name: url
      description: "URL do repositório Git"
      type: string
    - name: revision
      description: "Branch, tag ou commit hash para checkout"
      type: string
      default: "main"
  steps:
    - name: clone
      image: alpine/git # Usa uma imagem leve com Git
      script: |
        #!/bin/sh
        echo $(params.user)
        git clone https://$(params.user):$(params.password)@github.com/Sabrina51/delivery-pipelines-study.git


        git clone --branch=$(params.revision) $(params.url) $(workspaces.output.path)
    - name: install-cypress
      image: ubuntu
      script: |
        #!/bin/bash
        ls
        # ls -la $(workspaces.output.path)
        ls -la /workspace/output
