apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cypress-task
spec:
  workspaces:
    - name: workspace
  steps:
    - name: install-cypress
      image: ubuntu
      script: |
        #!/bin/bash
        ls
        ls -la $(workspaces.workspace.path)
        ls -la $(root.workspace.path)
        ls -la $(home.workspace.path)
        ls -la $(tekton.workspace.path)
        ls -la $(usr.workspace.path)
