apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: start-cypress-test
spec:
  steps:
    - name: cypress
      image: cypress/browsers:22.12.0
      command:
        - "cypress"
      args:
        - "run"

---

apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-cypress-tests
spec:
  taskRef:
    name: start-cypress-test