apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cypress-task
spec:
  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this workspace
  steps:
    - name: install-cypress
      image: ubuntu
      command:
        ["/bin/bash", "-c"]
        # - /bin/bash
        # args: ["-c", "echo hello world" ]
      args:
        - |

          echo "AAAAA"
          ls -la /workspace

---

apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-
  labels:
    tekton.dev/task: git-clone
spec:
  taskRef:
    name: cypress-task
  params:
    - name: url
      value: https://github.com/redhat-scholars/tekton-tutorial-greeter
    - name: revision
      value: master
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: tekton-tutorial-sources
