apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: output
  params:
    - name: url
    - name: token
  steps:
    - name: clone-repository
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
      script: |
        #!/bin/sh
        printf "\n====================== git clone ======================\n"
        echo "variaveis\n"
        echo "$token"
        echo $url
        echo "fim\n"
        git clone https://Sabrina51:$(params.token)@github.com/Sabrina51/delivery-pipelines-study.git $(workspaces.output.path)
    # - name: run-cypress
    #   image: cypress/browsers:latest
    #   workingDir: /workspace/output
    #   script: |
    #     #!/bin/bash
    #     printf "\n====================== install cypress ======================\n"
    #     npm ci
    #     printf "\n====================== run cypressn ======================\n"
    #     npm run cy:run