apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cypress-task
spec:
  steps:
    - name: git-clone
      image: ubuntu
      command:
        ["/bin/bash", "-c"]
        # - /bin/bash
        # args: ["-c", "echo hello world" ]
      args:
        - |
          ls
    - name: fetch-source
      image: ubuntu
      command:
        ["/bin/bash", "-c"]
        # - /bin/bash
        # args: ["-c", "echo hello world" ]
      args:
        - |
          ls
    - name: install-cypress
      image: ubuntu
      command:
        ["/bin/bash", "-c"]
        # - /bin/bash
        # args: ["-c", "echo hello world" ]
      args:
        - |
          ls
    - name: run-cypress
      image: ubuntu
      command:
        ["/bin/bash", "-c"]
        # - /bin/bash
        # args: ["-c", "echo hello world" ]
      args:
        - |
          ls
