apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cypress-task
spec:
  steps:
    # - name: git-clone
    #   image: ubuntu
    #   script: |
    #     #!/bin/sh
    #     echo "BANANA" > $(workspaces.sabrina.path)/cypress
    #     ls
    #   workspaces:
    #     - name: sabrina
    #       mountPath: /custom/path/relative/to/root
    # - name: install-cypress
    #   image: ubuntu
    #   command:
    #     ["/bin/bash", "-c"]
    #     # - /bin/bash
    #     # args: ["-c", "echo hello world" ]
    #   args:
    #     - |
    #       ls
    - name: run-cypress
      image: cypress/browsers:22.12.0
      command:
        - "cypress"
      args:
        - "run"

---

apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: run-cypress-tests2
spec:
  taskRef:
    name: cypress-task