apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: clone-repo
spec:
  workspaces:
    - name: git-repo
  steps:
    - name: install-cypress
      image: ubuntu
      script: |
        #!/bin/bash
        ls
        ls -la $(git-repo.workspace.path)
        ls -la /workspace/output
