apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cypress-task
spec:
  workspaces:
    - name: workspace
  steps:
    - name: install-cypress
      image: ubuntu
      script: |
        #!/bin/bash
        ls -la $(workspaces.workspace.path)
