apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: git-repo
spec:
  workspaces:
    - name: output
  steps:
    - name: install-cypress
      image: ubuntu
      script: |
        #!/bin/bash
        ls
        ls -la $(output.workspace.path)
        ls -la /workspace/output
