apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: cypress-task
spec:
  steps:
    - name: git-clone
      image: ubuntu
      script: |
        #!/bin/sh
        echo "BANANA" > $(workspaces.git-source.path)/cypress
        ls
      workspaces:
        - name: git-source
          mountPath: /custom/path/relative/to/root
    - name: install-cypress
      image: ubuntu
      command:
        ["/bin/bash", "-c"]
        # - /bin/bash
        # args: ["-c", "echo hello world" ]
      args:
        - |
          ls
    - name: run-cypress
      image: ubuntu
      command:
        ["/bin/bash", "-c"]
        # - /bin/bash
        # args: ["-c", "echo hello world" ]
      args:
        - |
          cd workspace/
          ls
