apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: output
  params:
    - name: url
      description: "URL do repositório Git"
      type: string
    - name: revision
      description: "Branch, tag ou commit hash para checkout"
      type: string
      default: "main"
    - name: token
  steps:
    - name: clone-repository
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.40.2
      script: |
        #!/bin/sh
        git clone https://Sabrina51:$(params.token)@github.com/Sabrina51/delivery-pipelines-study.git $(workspaces.output.path)
    - name: run-cypress
      image: cypress/browsers:latest
      workingDir: /workspace/output
      script: |
        #!/bin/bash
        ls -la
        printf "\n====================== install cypress ======================\n"
        npm ci
        npm run cy:run