apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: git-clone
spec:
  workspaces:
    - name: output
  params:
    - name: url
      description: "URL do repositório Git"
      type: string
    - name: revision
      description: "Branch, tag ou commit hash para checkout"
      type: string
      default: "main"
    - name: token
  steps:
    - name: clone-repo
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.15.2
      script: |
        #!/bin/sh
        git clone https://Sabrina51:$(params.token)@github.com/Sabrina51/delivery-pipelines-study.git $(workspaces.output.path)
        # git clone --branch=$(params.revision) $(params.url) $(workspaces.output.path)
    - name: install-cypress
      image: ubuntu
      script: |
        #!/bin/bash
        # ls -la /workspace/output

        printf "\n====================== apt-get update ======================\n"
        apt-get update

        printf "\n====================== apt-get install ======================\n"
        apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb -y

        cd /workspace/output
        ls

        printf "\n====================== cypress ci ======================\n"
        npm ci

        printf "\n====================== cypress verify ======================\n"
        npx run verify
    - name: run-cypress
      image: ubuntu
      script: |
        #!/bin/bash
        cd /workspace/output

        ls -la

        printf "\n ====================== cypress run ======================\n"
        npm run cy:run