apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
  - name: bananinha
    default: "amarela"
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: pipeline-run-
    spec:
      pipelineRef:
        name: simple-pipeline
      params:
      - name: bananinha
        value: $(params.bananinha)
      workspaces:
      - name: sabrina
        emptyDir: {}