apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: html_url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipeline-run-
      spec:
        pipelineRef:
          name: simple-pipeline
        workspaces:
          - name: git-source
            emptyDir: {} # Ou use um PVC
        params:
          - name: html_url
            value: $(params.html_url)
