apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: bananinha
      default: "amarela"
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipeline-run-
      spec:
        pipelineRef:
          name: simple-pipeline
      workspaces:
        - name: shared-workspace
          emptyDir: {} # Ou use um PVC
      params:
        - name: bananinha
          value: $(params.bananinha)
