apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: templateName
spec:
  params:
    - name: url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: simple-pipeline-run-
      spec:
        pipelineRef:
          name: clone-read-run-
        params:
          - name: url
            value: $(params.repo-url)
        workspaces:
          - name: git-source
            emptyDir: {}
